# Generated by Django 4.1 on 2022-08-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_rename_words_wordsdata_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordsdata',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
