# Generated by Django 4.1 on 2022-08-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_scoreboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoreboard',
            name='day',
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='score',
            field=models.CharField(default=0, max_length=18),
        ),
    ]
