# Generated by Django 4.1 on 2022-08-11 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_remove_scoreboard_day_alter_scoreboard_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreboard',
            name='day',
            field=models.IntegerField(default=0),
        ),
    ]
