# Generated by Django 4.1 on 2022-08-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_scoreboard_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scoreboard',
            old_name='day',
            new_name='day1',
        ),
        migrations.RemoveField(
            model_name='scoreboard',
            name='score',
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='day10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='day11',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='day12',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='day13',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='day14',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='day15',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='day16',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='day17',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='day18',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='day2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='day3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='day4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='day5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='day6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='day7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='day8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='day9',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='startday',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='totalscore',
            field=models.IntegerField(default=0),
        ),
    ]
