# Generated by Django 4.1 on 2022-08-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_rename_day_scoreboard_day1_remove_scoreboard_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreboard',
            name='day1',
            field=models.IntegerField(default='-'),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='day2',
            field=models.IntegerField(default='-'),
        ),
    ]
