# Generated by Django 4.1 on 2022-08-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_scoreboard_day1_alter_scoreboard_day2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreboard',
            name='day1',
            field=models.CharField(default='-', max_length=5),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='day10',
            field=models.CharField(default='-', max_length=5),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='day11',
            field=models.CharField(default='-', max_length=5),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='day12',
            field=models.CharField(default='-', max_length=5),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='day13',
            field=models.CharField(default='-', max_length=5),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='day14',
            field=models.CharField(default='-', max_length=5),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='day15',
            field=models.CharField(default='-', max_length=5),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='day16',
            field=models.CharField(default='-', max_length=5),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='day17',
            field=models.CharField(default='-', max_length=5),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='day18',
            field=models.CharField(default='-', max_length=5),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='day2',
            field=models.CharField(default='-', max_length=5),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='day3',
            field=models.CharField(default='-', max_length=5),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='day4',
            field=models.CharField(default='-', max_length=5),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='day5',
            field=models.CharField(default='-', max_length=5),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='day6',
            field=models.CharField(default='-', max_length=5),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='day7',
            field=models.CharField(default='-', max_length=5),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='day8',
            field=models.CharField(default='-', max_length=5),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='day9',
            field=models.CharField(default='-', max_length=5),
        ),
    ]
